config/routes.rb
Rails.application.routes.draw do
  get 'admin/login'
  root 'admin#login'
  get 'admin/logout'
  post 'admin/login'
  resources :student_profiles
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
    validates :firstName,:lastName, :mark1, :mark2, :mark3, presence: true
    has_one :StudentProfile, dependent: :destroy

    before_save :capitalizeName
    before_save :totalMarks

    before_destroy :deleteMessage

    def capitalizeName
        self.firstName.capitalize!
        self.lastName = self.lastName.capitalize
    end

    def totalMarks
        self.total = self.mark1 + self.mark2 + self.mark3
        self.percentage = (self.total / 3).round(2)
    end

    def deleteMessage
        logger.info "-------------------------#{self.firstName} is deleted Successfully....--------------------"
    end
end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord
  belongs_to :Student
  mount_uploader :image, FileUploader
  validates :age,:email, :image, :mobile, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def login
    if request.post?
      if params[:username] == "admin" && params[:password] == "admin@123"
        session[:admin] = "admin"
        flash[:notice] = "Welcome User, you are Successfully Login...!"
        redirect_to :controller=>:students, :action=>:index
      else
        flash[:notice] = "Invalid User and Password...!"
        render :action=>:login
      end
    end
  end
  def logout 
    flash[:notice] = "you are successfully logout...!"
    session[:admin] = nil
    redirect_to :controller=>:admin, :action=>:login
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/student_profiles_controller.rb
class StudentProfilesController < ApplicationController
  before_action :set_student_profile, only: %i[ show edit update destroy ]
  before_action :admin_loggedin?, only: %i[ new create edit update destroy ]
 # GET /student_profiles or /student_profiles.json
  def index
    @student_profiles = StudentProfile.all
  end

  # GET /student_profiles/1 or /student_profiles/1.json
  def show
  end

  # GET /student_profiles/new
  def new
    @student_profile = StudentProfile.new
  end

  # GET /student_profiles/1/edit
  def edit
  end

  # POST /student_profiles or /student_profiles.json
  def create
    @student_profile = StudentProfile.new(student_profile_params)

    respond_to do |format|
      if @student_profile.save
        format.html { redirect_to student_profile_url(@student_profile), notice: "Student profile was successfully created." }
        format.json { render :show, status: :created, location: @student_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_profiles/1 or /student_profiles/1.json
  def update
    respond_to do |format|
      if @student_profile.update(student_profile_params)
        format.html { redirect_to student_profile_url(@student_profile), notice: "Student profile was successfully updated." }
        format.json { render :show, status: :ok, location: @student_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_profiles/1 or /student_profiles/1.json
  def destroy
    @student_profile.destroy

    respond_to do |format|
      format.html { redirect_to student_profiles_url, notice: "Student profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_profile
      @student_profile = StudentProfile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_profile_params
      params.require(:student_profile).permit(:name, :age, :email, :address, :mobile, :Student_id, :image)
    end

    def admin_loggedin?
      if session[:admin].nil?
        flash[:notice] = "You need to Login as Admin...!"
        redirect_to admin_login_path
      end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :admin_loggedin?, only: %i[ new create edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        PostManMailer.alert_admin.deliver
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:firstName, :lastName, :mark1, :mark2, :mark3, :total, :percentage)
    end

    def admin_loggedin?
      if session[:admin].nil?
        flash[:notice] = "You need to Login as Admin...!"
        redirect_to admin_login_path
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/login.html.erb
<div class="homepage p-5" >
  <div class="card shadow rounded" style="height: auto; width: 305px; background-color: transparent;">
  <%= flash[:notice]%>
    <div class="card-body"  style="padding: 35px;">
      <div class=" text-center">
        <h4>Log In</h4>
      </div>
      <%= form_with do |f| %>
        <br/>
        <div class="field mb-3">
          <%= f.text_field :username, autofocus: true, class:"form-control", placeholder:"Username" %>
        </div>

        <div class="field mb-3">
          <%= f.password_field :password, class:"form-control", placeholder:"Password" %>
        </div>
        <br/>
        <div class="actions text-center">
          <%= f.submit "Log in", class:"form-control btn btn-secondary" %>
        </div>
      <% end %>
      <br/>
    </div>
  </div>
</div>
















<div class="homepage">
<%= flash[:notice]%>
<h2 >Sign In</h2>
<%= form_with do |f| %>
    <%= f.text_field :username%>
    <%= f.password_field :password %>
    <%= f.submit "Sign In!" %>
<% end %>
<div>
         

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
   <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>MsUniversity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'MsUniversity', admin_login_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to 'Result', students_path,class:"nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Profile', student_profiles_path, class:"nav-link" %>
      </li>
        <% if session[:admin] %>
          <li class="nav-item">
            <%= link_to 'Logout', admin_logout_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', admin_login_path, class:"nav-link" %>
          </li>
        <% end %>
        </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
      <%= yield %>
  </body>
</html>

app/views/student_profiles/_form.html.erb
<div class="card-body">
<%= form_with(model: student_profile, local: true) do |form| %>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age,class:"form-control" %>
    <p style="color: red"> <%= student_profile.errors.full_messages_for(:age).first if student_profile.errors.any? %></p>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email,class:"form-control" %>
    <p style="color: red"> <%= student_profile.errors.full_messages_for(:email).first if student_profile.errors.any? %></p>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address,class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.number_field :mobile,class:"form-control" %>
    <p style="color: red"> <%= student_profile.errors.full_messages_for(:mobile).first if student_profile.errors.any? %></p>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image,class:"form-control" %>
    <p style="color: red"> <%= student_profile.errors.full_messages_for(:image).first if student_profile.errors.any? %></p>
  </div>

  <div class="field">
    <%= form.label :Student_id %>
    <%= form.select :Student_id, Student.all.collect {|s| [s.firstName + " " + s.lastName,s.id]}, include_blank: true%>
    <p style="color: red"> <%= student_profile.errors.full_messages_for(:Student_id).first if student_profile.errors.any? %></p>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/student_profiles/edit.html.erb
<div class= "card p-3 cardcss1">

<div class= "card cardboarder1">
<div class="card-header">
    <h4><b>Update Student Profile<b></h4>
  </div>
<%= render 'form', student_profile: @student_profile %>
<%= link_to 'Back', student_profiles_path, class:"btn btn-warning" %>
</div>
</div>
</div>

app/views/student_profiles/index.html.erb
<div class="alert" id ="notice" role="alert">
  <%= notice %>
</div>
<div class= "card p-3 cardcss1">
  <div class="rightcss">
    <%= link_to 'New Student Profile', new_student_profile_path, class:"btn btn-warning" %>
  <div>
<br/><br/>
<table class="table table-bordered shadow">
  <thead class="table-dark">
    <tr>
      <th>Student</th>
      <th>Age</th>
      <th>Email</th>
      <th>Address</th>
      <th>Mobile</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table-light">
    <% @student_profiles.each do |student_profile| %>
      <tr>
        <td><%= student_profile.Student.firstName + " " + student_profile.Student.lastName%></td>
        <td><%= student_profile.age %></td>
        <td><%= student_profile.email %></td>
        <td><%= student_profile.address %></td>
        <td><%= student_profile.mobile %></td>
        <td><img src="<%= student_profile.image %>" width="50" height="100"></td>
        <td><%= link_to 'Show', student_profile %></td>
        <td><%= link_to 'Edit', edit_student_profile_path(student_profile) %></td>
        <td><%= button_to 'Destroy', student_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/student_profiles/new.html.erb
<div class= "card p-3 cardcss1">

<div class= "card cardboarder1">
<div class="card-header">
    <h4><b>New Student Profile<b></h4>
  </div>
  <%= render 'form', student_profile: @student_profile %>

<%= link_to 'Back', student_profiles_path, class:"btn btn-warning" %>
</div>
</div>
</div>

app/views/student_profiles/show.html.erb
<div class= "card p-3 cardcss1">

<div class= "card cardboarder1">
<div class="card-header ">


<p id="notice"><%= notice %></p>


<div class="row">
    <div class="col">
    <h3><b>
      <%= @student_profile.Student.firstName+" " +@student_profile.Student.lastName %>
    </b></h3>
    <hr>
    <h6>
      <strong>Age:</strong>
      <%= @student_profile.age %>
    </h6>
    
    <h6>
      <strong>Email:</strong>
      <%= @student_profile.email %>
    </h6>
    
    <h6>
      <strong>Address:</strong>
      <%= @student_profile.address %>
    </h6>
    
    <h6>
      <strong>Mobile:</strong>
      <%= @student_profile.mobile %>
    </h6>
  
  
    </div>
    <div class="col col-lg-2">
    <p>
      <img src="<%= @student_profile.image %>" width="150" height="200">
    </p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to 'Edit', edit_student_profile_path(@student_profile),class:"btn btn-primary" %> 
    </div>
    <div class="col">
      <%= link_to 'Back', student_profiles_path ,class:"btn btn-secondary"%>
    </div> 
  </div> 
</div>
</div>    
</div>

app/views/students/_form.html.erb
<div class="card-body">
<%= form_with(model: student, local: true) do |form| %>

  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName,class:"form-control" %>
    <p style="color: red"> <%= student.errors.full_messages_for(:firstName).first if student.errors.any? %></p>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName, class:"form-control" %>
    <p style="color: red"> <%= student.errors.full_messages_for(:lastName).first if student.errors.any? %></p>

  </div>

  <div class="field">
    <%= form.label "Ruby on Rails" %>
    <%= form.number_field :mark1, class:"form-control" %>
    <p style="color: red"> <%= student.errors.full_messages_for(:mark1).first if student.errors.any? %></p>
  </div>

  <div class="field">
    <%= form.label "React Js" %>
    <%= form.number_field :mark2, class:"form-control" %>
    <p style="color: red"> <%= student.errors.full_messages_for(:mark2).first if student.errors.any? %></p>
  </div>

  <div class="field">
    <%= form.label "Node Js" %>
    <%= form.number_field :mark3, class:"form-control" %>
    <p style="color: red"> <%= student.errors.full_messages_for(:mark3).first if student.errors.any? %></p>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class= "card p-3 cardcss1">

<div class= "card cardboarder1">
<div class="card-header">
    <h4><b>Update Student Details<b></h4>
  </div>
<%= render 'form', student: @student %>
<%= link_to 'Back', students_path, class:"btn btn-warning" %>
</div>
</div>
</div>

app/views/students/index.html.erb
<div class="alert" id ="notice" role="alert">
  <%= notice %>
</div>
<div class= "card p-3 cardcss1">
  <div class="rightcss">
  <%= link_to 'New Student', new_student_path, class:"btn btn-warning" %>
  <div>
<br/><br/>
<table class="table table-bordered shadow">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email ID</th>
      <th>Ruby on Rails</th>
      <th>React Js</th>
      <th>Node Js</th>
      <th>Total</th>
      <th>Percentage</th>
     
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody class="table-light">
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.firstName + " "+ student.lastName, student %></td>
        <td><%= student.mark1 %></td>
        <td><%= student.mark2 %></td>
        <td><%= student.mark3 %></td>
        <td><%= student.total %></td>
        <td><%= student.percentage %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class:"btn btn-outline-secondary" %></td>
        <td><%= button_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<br>

app/views/students/new.html.erb
<div class= "card p-3 cardcss1">

<div class= "card cardboarder1">
<div class="card-header">
    <h4><b>New Student Details<b></h4>
  </div>
<%= render 'form', student: @student %>

<%= link_to 'Back', students_path, class:"btn btn-warning" %>
</div>
</div>
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', students_path, class:"btn btn-secondary" %>
<div class="resultcss" >
<div class= "card p-3 cardcss">
<div class= "card cardboarder">
<div class="card-body">
<div class="headtag">
<h5><b>THE MAHARAJA SAYAJIRAO UNIVERSITY OF BARODA<b></h5>
<p><b>Vadodara - 390 002, Gujarat, India</b></p>
</div>
<div class="tagcss">
<h6><b>Statenment of Marks for First Semester of BE-I(Computer Science)<br/>  Faculty of Technology - Bachelor of Engineering<br/>                     Examination:April:2022<b></h6>
</div>
<br/>
<br/>

  <div class="row">
    <div class="col">
    <p>
    <strong>Name:</strong>
    <%= @student.firstName.upcase + "  " +  @student.lastName.upcase %>
  </p>
  
  <p>
    <strong>Student ID:</strong>
    <%= @student.id %>
  </p>   
  
  <p>
    <strong>Faculty/College/Institution:</strong>
    Faculty Of Technology and Engineering
  </p>
  
    </div>
    <div class="col col-lg-2">
    <p>
    <%if  @student.StudentProfile %>
      <img src="<%= @student.StudentProfile.image %>" width="65" height="100">
    <%end%>
    </p>
    </div>
  </div>



<br/>
<br/>


<table class="table table-bordered shadow">
  <thead class="table-dark">
    <tr>
      <th>Course</th>
      <th>Max Marks</th>
      <th>Min Marks</th>
      <th>Obtained Marks</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>Ruby On Rails</td>
        <td> 100 </td>
        <td> 30 </td><td>
        <%= @student.mark1 %></td>
      </tr>
      <tr>
        <td>React Js</td>
        <td> 100 </td>
        <td> 30 </td><td>
        <%= @student.mark2 %></td>
      </tr>
      <tr>
        <td>Node Js</td>
        <td> 100 </td>
        <td> 30 </td>
        <td><%= @student.mark3 %></td>
      </tr>
      <tr>
        <td colspan="1">Total</td>
        <td colspan="3" ><%= @student.total %> out of 300(Three Hundred)</td>
      </tr>
      <tr>
        <td colspan="1">Percentage</td>
        <td colspan="3"><%=@student.percentage %> %</td>
      </tr>
  </tbody>
</table>
<br/>
<br/>
<br/>
<br/>
<br/>
<p>
  <strong>Deputy Register</strong><br/>
  (Examination)
</p>
</div>
</div>
</div>
</div>